### PR TITLE
Feature/add bip 08 support

### PR DESCRIPTION
**Pull request by cameri**
```json
{
  "id": "13937d900a66689c73d1d21d3acfd84fe88aa971d2e6f843e2260db1402d0b9c",
  "pubkey": "4d7dd477c4b208b253c8842dbb9cfb21acf815d3d83dc458e9e68aded707733d",
  "created_at": 1642991018,
  "kind": 1,
  "tags": [
    [
      "p",
      "22e804d26ed16b68db5259e78449e96dab5d464c8f470bda3eb1a70467f2c793"
    ]
  ],
  "content": "this is a really long as message, we are seeing what's gonna happen when we put a mention on it\nthis is a really long as message, we are seeing what's gonna happen when we put a mention on it\nthis is a really long \n#[0]",
  "sig": "9415a880ee6fa4b3ab88a4db6d24c1a640b10ecbba8941c83e3a58ac841f39829652ae760ee2e8eb6797c8be3b8523853471188ad6e460acdf3d9d5d76276cab"
}
```
image

```json
{
  "id": "98f947887068cd7089fa363c7eea62ff6d36d5b3fd527135755c6099bfc43bd9",
  "pubkey": "4d7dd477c4b208b253c8842dbb9cfb21acf815d3d83dc458e9e68aded707733d",
  "created_at": 1642970797,
  "kind": 1,
  "tags": [
    [
      "p",
      "27866e9d854c78ae625b867eefdfa9580434bc3e675be08d2acb526610d96fbe"
    ],
    [
      "p",
      "1d643df20fb811b33c3cfb04c72db04c6ae031dbf68f613ba45407cbdd9446b6"
    ]
  ],
  "content": "Hello #[0] how is #[1] doing?",
  "sig": "f1d80d3b9a66c7461784f15eb5dfdfec952d3802fb9c7712993da7d0fd6175a360beb559733656b03e7c0e91335253024f7d350e31916001ccd3e2856decac59"
}
```
image

### CODE REVIEW

**Comment by fiatjaf** [comment]
Why have you removed the trimmed+showmore icon thing?

**Comment by cameri** [comment]
It breaks Markdown around the 270 character mark. It needs to be done in a smart way so it doesn't cut the text breaking what the user sees.
I can write a plugin for Markdown that does it in a smart way. 
I'll be fixing that in another PR if that's okay. If you want me to add it back I can do that too.
Let me know.

**Comment by fiatjaf** [comment]
I think that's an important feature to have, to prevent timelines from becoming piles of large spam text like Facebook -- even if it breaks.

But since you promised to fix it later then I can wait for that.

**Comment by cameri** [comment]
With mention stuff kind of done, I'll be fixing the trimming/shortening of Markdown

**Pull request merged**
